apiVersion: v1
kind: Service
metadata:
  name: website-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: website
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: website
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: gitdata
      volumes:
      - name: gitdata
        gitRepo:
          repository: https://github.com/spohnan/kube-site-test.git
          revision: 59c1620f313f364bd268d506299756307dc9ecf6
