apiVersion: v1
kind: Service
metadata:
  name: website-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: website
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: website-v201605302044
spec:
  replicas: 2
  selector:
    app: website
    ver: v201605302044
  template:
    metadata:
      labels:
        app: website
        ver: v201605302044
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: gitdata
      volumes:
      - name: gitdata
        gitRepo:
          repository: https://github.com/spohnan/kube-site-test.git
          revision: 249c312118e27104fb6423485ebf8e22f68a4a2b
